export type Product = {
  id: string;
  name: string;
  category: "buidan" | "sandal" | "shiree" | "or" | "shuugee";
  categoryName: string;
  price: number;
  images: string[];
  description: string;
  material: string;
  dimensions: string;
  inStock: number;
  featured?: boolean;
};

export const categories = [
  { id: "buidan", name: "Буйдан" },
  { id: "sandal", name: "Сандал" },
  { id: "shiree", name: "Ширээ" },
  { id: "or", name: "Ор" },
  { id: "shuugee", name: "Шүүгээ" },
];

export const initialProducts: Product[] = [
  // Буйдан (Beds)
  {
    id: "bed-001",
    name: "Орчин үеийн хар буйдан",
    category: "buidan",
    categoryName: "Буйдан",
    price: 2800000,
    images: ["https://picsum.photos/500/500?random=1"],
    description: "Өндөр чанартай модон хар буйдан, маш сайхан дизайнтай",
    material: "Хөлөг модон",
    dimensions: "200 × 160 × 100 см",
    inStock: 3,
    featured: true,
  },
  {
    id: "bed-002",
    name: "Эмгэнэлтэй буйдан",
    category: "buidan",
    categoryName: "Буйдан",
    price: 1950000,
    images: ["https://picsum.photos/500/500?random=2"],
    description: "Цэвэрхэн, минимал дизайнтай буйдан",
    material: "Нарс",
    dimensions: "190 × 140 × 80 см",
    inStock: 2,
  },
  {
    id: "bed-003",
    name: "Төмөрцөг буйдан",
    category: "buidan",
    categoryName: "Буйдан",
    price: 1200000,
    images: ["https://picsum.photos/500/500?random=3"],
    description: "Өнгөлөгдсөн төмөрцөг хүүхэлтэй буйдан",
    material: "Өнгөлөгдсөн төмөр",
    dimensions: "180 × 100 × 90 см",
    inStock: 5,
  },
  {
    id: "bed-004",
    name: "Элит буйдан",
    category: "buidan",
    categoryName: "Буйдан",
    price: 4500000,
    images: ["https://picsum.photos/500/500?random=4"],
    description: "Хар модон, урт байдалтай, люкс буйдан",
    material: "Элитийн модон",
    dimensions: "210 × 170 × 120 см",
    inStock: 1,
    featured: true,
  },

  // Сандал (Chairs)
  {
    id: "chair-001",
    name: "Орчин үеийн сандал",
    category: "sandal",
    categoryName: "Сандал",
    price: 450000,
    images: ["https://picsum.photos/500/500?random=5"],
    description: "Хөл ороогүй, маш сайхан дизайнтай сандал",
    material: "Нарс",
    dimensions: "60 × 70 × 85 см",
    inStock: 8,
  },
  {
    id: "chair-002",
    name: "Лофт сандал",
    category: "sandal",
    categoryName: "Сандал",
    price: 650000,
    images: ["https://picsum.photos/500/500?random=6"],
    description: "Төмөр хүндэлэгтэй хөлтэй сандал",
    material: "Өнгөлөгдсөн төмөр",
    dimensions: "55 × 65 × 90 см",
    inStock: 6,
    featured: true,
  },
  {
    id: "chair-003",
    name: "Ажлын сандал",
    category: "sandal",
    categoryName: "Сандал",
    price: 850000,
    images: ["https://picsum.photos/500/500?random=7"],
    description: "Сүүлтэй, сэтэлгээтэй сандал, сайн амралтын мэдрэмж",
    material: "Байгалийн эдлэл",
    dimensions: "65 × 70 × 100 см",
    inStock: 3,
  },
  {
    id: "chair-004",
    name: "Гүргөм сандал",
    category: "sandal",
    categoryName: "Сандал",
    price: 320000,
    images: ["https://picsum.photos/500/500?random=8"],
    description: "Энгийн, хөндлөнө сандал",
    material: "Нарс",
    dimensions: "50 × 55 × 80 см",
    inStock: 12,
  },

  // Ширээ (Tables)
  {
    id: "table-001",
    name: "Идэвхтэй ширээ",
    category: "shiree",
    categoryName: "Ширээ",
    price: 1500000,
    images: ["https://picsum.photos/500/500?random=9"],
    description: "Том хэмжээтэй ер бүрийн ширээ, гэрийн хэрэглээнд сайн",
    material: "Хөлөг модон",
    dimensions: "150 × 90 × 75 см",
    inStock: 2,
    featured: true,
  },
  {
    id: "table-002",
    name: "Хэвлэл ширээ",
    category: "shiree",
    categoryName: "Ширээ",
    price: 680000,
    images: ["https://picsum.photos/500/500?random=10"],
    description: "Өндөргүй, өндрийн цаасны ширээ",
    material: "Нарс",
    dimensions: "100 × 60 × 45 см",
    inStock: 7,
  },
  {
    id: "table-003",
    name: "Орчин үеийн стол",
    category: "shiree",
    categoryName: "Ширээ",
    price: 2200000,
    images: ["https://picsum.photos/500/500?random=11"],
    description: "Төмөр хүндэлэгтэй төлөвлөгдсөн ширээ",
    material: "Өнгөлөгдсөн төмөр",
    dimensions: "160 × 80 × 75 см",
    inStock: 1,
  },
  {
    id: "table-004",
    name: "Минимал ширээ",
    category: "shiree",
    categoryName: "Ширээ",
    price: 950000,
    images: ["https://picsum.photos/500/500?random=12"],
    description: "Цэвэрхэн нэгэн өнгийн ширээ",
    material: "Үе-үе модон",
    dimensions: "120 × 70 × 75 см",
    inStock: 4,
  },

  // Ор (Bed frames/Base)
  {
    id: "base-001",
    name: "Модон суух ор",
    category: "or",
    categoryName: "Ор",
    price: 780000,
    images: ["https://picsum.photos/500/500?random=13"],
    description: "Хөндлөнө суух ор, хөндлөн ба хөнгөн өнгөтэй",
    material: "Нарс",
    dimensions: "180 × 90 × 85 см",
    inStock: 5,
  },
  {
    id: "base-002",
    name: "Төмөр суух ор",
    category: "or",
    categoryName: "Ор",
    price: 620000,
    images: ["https://picsum.photos/500/500?random=14"],
    description: "Төмөрцөг, бөөхэн хөлтэй суух ор",
    material: "Өнгөлөгдсөн төмөр",
    dimensions: "160 × 85 × 80 см",
    inStock: 3,
  },
  {
    id: "base-003",
    name: "Люкс суух ор",
    category: "or",
    categoryName: "Ор",
    price: 1300000,
    images: ["https://picsum.photos/500/500?random=18"],
    description: "Гүнэгтэй, урамшилтай суух ор",
    material: "Байгалийн эдлэл",
    dimensions: "190 × 95 × 90 см",
    inStock: 2,
    featured: true,
  },

  // Шүүгээ (Cabinets/Storage)
  {
    id: "storage-001",
    name: "Эргэдэг шүүгээ",
    category: "shuugee",
    categoryName: "Шүүгээ",
    price: 2100000,
    images: ["https://picsum.photos/500/500?random=15"],
    description: "Том эргэлтэй, олон өнгийн шүүгээ",
    material: "Хөлөг модон",
    dimensions: "200 × 60 × 240 см",
    inStock: 1,
    featured: true,
  },
  {
    id: "storage-002",
    name: "Идэвхтэй шүүгээ",
    category: "shuugee",
    categoryName: "Шүүгээ",
    price: 1400000,
    images: ["https://picsum.photos/500/500?random=16"],
    description: "Гөлгөр давхраат шүүгээ",
    material: "Нарс",
    dimensions: "160 × 50 × 200 см",
    inStock: 2,
  },
  {
    id: "storage-003",
    name: "Төмөр шүүгээ",
    category: "shuugee",
    categoryName: "Шүүгээ",
    price: 1650000,
    images: ["https://picsum.photos/500/500?random=17"],
    description: "Лофт төмөрцөг шүүгээ",
    material: "Өнгөлөгдсөн төмөр",
    dimensions: "180 × 55 × 220 см",
    inStock: 0,
  },
  {
    id: "storage-004",
    name: "Минимал шүүгээ",
    category: "shuugee",
    categoryName: "Шүүгээ",
    price: 950000,
    images: ["https://picsum.photos/500/500?random=19"],
    description: "Цэвэрхэн дизайнтай, үе-үе мод",
    material: "Үе-үе модон",
    dimensions: "150 × 45 × 180 см",
    inStock: 4,
  },
];

export const formatPrice = (price: number) =>
  new Intl.NumberFormat("mn-MN").format(price) + "₮";
